# Step 1: Build Stage
FROM node:22

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY pnpm-lock.yaml package.json ./
RUN npm install -g pnpm && pnpm install

# Copy the rest of the source code
COPY . .

# Build TypeScript to JavaScript
RUN pnpm build

